"""Site generation primitives for mkpages."""

from __future__ import annotations

import base64
import json
import os
import re
import shutil
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Iterable

try:
    from importlib.resources import files
except ImportError:  # pragma: no cover
    from importlib_resources import files  # type: ignore


OUTPUT_MARKER = ".mkpages-output"
DEV_RELOAD_TOKEN_PATH = PurePosixPath("assets/mkpages-preview-token.txt")
SOCIAL_CARD_PATH = PurePosixPath("assets/_mkpages/social-card.svg")
DEFAULT_THEME_RESOURCE = "themes/default.css"
TEMPLATE_DIR = "templates"
CONFIG_FILE_NAME = "mkpages.yml"
BUNDLED_THEMES = {
    "default": "themes/default.css",
    "dark": "themes/dark.css",
    "developer": "themes/developer.css",
    "matrix": "themes/matrix.css",
    "minimal": "themes/minimal.css",
    "pulsar": "themes/pulsar.css",
    "retro": "themes/retro.css",
}
THEME_CARD_TEMPLATES = {
    "default": "default",
    "dark": "dark",
    "developer": "dark",
    "matrix": "dark",
    "minimal": "default",
    "pulsar": "dark",
    "retro": "default",
}
SUPPORTED_CARD_TEMPLATES = frozenset({"default", "dark"})
EXCLUDED_NAMES = {
    ".git",
    ".github",
    ".mkpages",
    "_site",
    ".venv",
    "venv",
    "__pycache__",
}
MARKDOWN_LINK_RE = re.compile(r"(?P<prefix>!?\[[^\]]*\]\()(?P<target>[^)]+)(?P<suffix>\))")
H1_RE = re.compile(r"^#\s+(?P<title>.+?)\s*$", re.MULTILINE)
FRONT_MATTER_RE = re.compile(r"\A---\s*\n(?P<front>.*?)\n---\s*\n?", re.DOTALL)
FRONT_MATTER_KEY_RE = re.compile(r"^(?P<key>[A-Za-z_][A-Za-z0-9_-]*)\s*:", re.MULTILINE)
CARDS_DIRECTIVE_RE = re.compile(
    r"^:::(?P<name>cards)(?P<args>[^\n]*)\n(?P<body>.*?)^:::\s*$",
    re.MULTILINE | re.DOTALL,
)
DIRECTIVE_ARG_RE = re.compile(r"(?P<key>[A-Za-z_][A-Za-z0-9_-]*)=(?P<value>\S+)")


class MkpagesError(RuntimeError):
    """Raised when site generation cannot continue safely."""


@dataclass(frozen=True)
class Page:
    """Represents a source markdown file and its generated route."""

    source_rel: PurePosixPath
    route_rel: PurePosixPath
    output_rel: PurePosixPath

    @property
    def route_url(self) -> str:
        """Return the site URL for this page."""
        route = str(self.route_rel).strip(".")
        if not route:
            return "/"
        return "/" + route.strip("/") + "/"


@dataclass(frozen=True)
class GenerationResult:
    """Summary of one generation run."""

    output_dir: Path
    pages_written: int
    assets_copied: int


@dataclass(frozen=True)
class NavigationItem:
    """Represents one configured navigation link."""

    label: str
    href: str


@dataclass(frozen=True)
class CardConfig:
    """Represents optional social card overrides."""

    enabled: bool = True
    template: str | None = None
    title: str | None = None
    description: str | None = None
    logo: PurePosixPath | None = None
    image: PurePosixPath | None = None


@dataclass(frozen=True)
class SiteConfig:
    """Represents optional mkpages site configuration."""

    title: str | None = None
    description: str | None = None
    theme: str | None = None
    favicon: PurePosixPath | None = None
    navigation: tuple[NavigationItem, ...] = ()
    card: CardConfig = CardConfig()


@dataclass(frozen=True)
class ResolvedCard:
    """Represents the effective social card metadata for the generated site."""

    enabled: bool
    title: str
    description: str
    site_name: str
    template: str
    image_path: PurePosixPath
    generated: bool
    art_path: Path | None = None


@dataclass(frozen=True)
class ResolvedTheme:
    """Represents the effective theme path and optional bundled theme name."""

    path: Path
    name: str | None


@dataclass(frozen=True)
class SocialCardContext:
    """Represents the render context for a managed social card template."""

    title: str
    site_name: str
    description_markup: str
    logo_markup: str
    description_fill: str
    title_x: str
    title_y: str


@dataclass(frozen=True)
class ContentEntry:
    """Represents front-matter-backed content that can feed directives."""

    page: Page
    title: str
    description: str
    metadata: dict[str, object]


def generate_site(
    content_root: Path,
    output_dir: Path,
    explicit_theme: str | Path | None = None,
    preserve_output_names: tuple[str, ...] = (),
    allow_unmarked_reuse: bool = False,
    dev_reload_token: str | None = None,
) -> GenerationResult:
    """Generate a Jekyll source tree from a markdown content root."""
    markdown_files = find_markdown_files(content_root)
    page_map = build_page_map(markdown_files)
    content_index = build_content_index(content_root, page_map)
    site_config = load_site_config(content_root)
    site_title = site_config.title or infer_site_title(content_root)
    site_description = site_config.description or "Generated by mkpages"
    resolved_theme = resolve_theme(content_root, explicit_theme, site_config.theme)
    resolved_card = resolve_social_card(
        content_root,
        site_title=site_title,
        site_description=site_description,
        card_config=site_config.card,
        theme_name=resolved_theme.name,
        favicon=site_config.favicon,
    )

    prepare_output_dir(
        output_dir,
        preserve_names=preserve_output_names,
        allow_unmarked_reuse=allow_unmarked_reuse,
    )
    write_marker(output_dir)
    write_site_files(
        output_dir,
        site_title=site_title,
        site_description=site_description,
        navigation=site_config.navigation,
        favicon=site_config.favicon,
        theme_path=resolved_theme.path,
        dev_reload_token=dev_reload_token,
        resolved_card=resolved_card,
    )

    pages_written = 0
    for page in page_map.values():
        write_page(content_root, output_dir, page, page_map, content_index)
        pages_written += 1

    assets_copied = copy_non_markdown_files(content_root, output_dir)
    return GenerationResult(
        output_dir=output_dir, pages_written=pages_written, assets_copied=assets_copied
    )


def find_markdown_files(content_root: Path) -> list[PurePosixPath]:
    """Return markdown files under the content root, excluding unsafe directories."""
    results: list[PurePosixPath] = []
    for path in sorted(content_root.rglob("*.md")):
        rel_path = path.relative_to(content_root)
        if is_excluded(rel_path):
            continue
        results.append(PurePosixPath(rel_path.as_posix()))
    return results


def build_page_map(markdown_files: Iterable[PurePosixPath]) -> dict[PurePosixPath, Page]:
    """Map source markdown files to generated routes and output paths."""
    source_paths = set(markdown_files)
    return {
        source_rel: Page(
            source_rel=source_rel,
            route_rel=route_for(source_rel, source_paths),
            output_rel=output_path_for(source_rel, source_paths),
        )
        for source_rel in sorted(source_paths)
    }


def route_for(source_rel: PurePosixPath, source_paths: set[PurePosixPath]) -> PurePosixPath:
    """Resolve the output route for a markdown file."""
    if source_rel.name == "index.md":
        return source_rel.parent
    if (
        source_rel.name == "README.md"
        and source_rel.parent.joinpath("index.md") not in source_paths
    ):
        return source_rel.parent
    return source_rel.parent / source_rel.stem


def output_path_for(source_rel: PurePosixPath, source_paths: set[PurePosixPath]) -> PurePosixPath:
    """Resolve the generated markdown path within the output tree."""
    route_rel = route_for(source_rel, source_paths)
    if str(route_rel) in {"", "."}:
        return PurePosixPath("index.md")
    return route_rel / "index.md"


def prepare_output_dir(
    output_dir: Path,
    preserve_names: tuple[str, ...] = (),
    allow_unmarked_reuse: bool = False,
) -> None:
    """Ensure the output directory can be safely overwritten."""
    if not output_dir.exists():
        output_dir.mkdir(parents=True)
        return
    if not output_dir.is_dir():
        raise MkpagesError(f"output path is not a directory: {output_dir}")

    marker_path = output_dir / OUTPUT_MARKER
    existing_entries = list(output_dir.iterdir())
    if (
        existing_entries
        and not marker_path.exists()
        and not (allow_unmarked_reuse and looks_like_recoverable_mkpages_output(existing_entries))
    ):
        raise MkpagesError(
            f"refusing to overwrite non-mkpages directory without marker: {output_dir}"
        )

    for child in existing_entries:
        if child.name in preserve_names:
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def looks_like_recoverable_mkpages_output(existing_entries: list[Path]) -> bool:
    """Return True for a stale default mkpages output directory we can safely recover."""
    allowed_names = {
        "_config.yml",
        "_includes",
        "_layouts",
        "assets",
        "_site",
        ".jekyll-cache",
        ".jekyll-metadata",
        ".sass-cache",
    }
    entry_names = {entry.name for entry in existing_entries}
    if not entry_names or not entry_names.issubset(allowed_names):
        return False
    return bool(entry_names & {"_config.yml", "_includes", "_layouts", "assets", "_site"})


def write_marker(output_dir: Path) -> None:
    """Write the output safety marker."""
    (output_dir / OUTPUT_MARKER).write_text("generated by mkpages\n", encoding="utf-8")


def write_site_files(
    output_dir: Path,
    site_title: str,
    site_description: str,
    navigation: tuple[NavigationItem, ...],
    favicon: PurePosixPath | None,
    theme_path: Path,
    dev_reload_token: str | None,
    resolved_card: ResolvedCard,
) -> None:
    """Write the shared Jekyll config, layout, includes, and theme."""
    write_config(output_dir, site_title, site_description)
    write_layouts(output_dir, navigation, favicon, dev_reload_token, resolved_card)
    write_theme(output_dir, theme_path)
    write_dev_reload_token(output_dir, dev_reload_token)
    write_social_card(output_dir, resolved_card)


def write_config(output_dir: Path, site_title: str, site_description: str) -> None:
    """Write a minimal Jekyll configuration file."""
    config = render_template(
        "config.yml.j2",
        site_title=json.dumps(site_title),
        site_description=json.dumps(site_description),
    )
    (output_dir / "_config.yml").write_text(config, encoding="utf-8")


def write_layouts(
    output_dir: Path,
    navigation: tuple[NavigationItem, ...],
    favicon: PurePosixPath | None,
    dev_reload_token: str | None,
    resolved_card: ResolvedCard,
) -> None:
    """Write the shared layout and includes."""
    layout_dir = output_dir / "_layouts"
    includes_dir = output_dir / "_includes"
    layout_dir.mkdir(parents=True, exist_ok=True)
    includes_dir.mkdir(parents=True, exist_ok=True)

    (layout_dir / "default.html").write_text(
        render_template(
            "default.html.j2",
            favicon_markup=build_favicon_markup(favicon),
            dev_reload_markup=build_dev_reload_markup(dev_reload_token),
            social_card_markup=build_social_card_markup(resolved_card),
        ),
        encoding="utf-8",
    )

    (includes_dir / "site_header.html").write_text(
        render_template(
            "site_header.html.j2", navigation_markup=build_navigation_markup(navigation)
        ),
        encoding="utf-8",
    )

    (includes_dir / "site_footer.html").write_text(
        render_template("site_footer.html.j2"),
        encoding="utf-8",
    )


def write_theme(output_dir: Path, theme_path: Path) -> None:
    """Copy the active site theme into the generated output."""
    assets_dir = output_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(theme_path, assets_dir / "site.css")


def write_dev_reload_token(output_dir: Path, dev_reload_token: str | None) -> None:
    """Write the preview-only reload token file when enabled."""
    token_path = output_dir / Path(DEV_RELOAD_TOKEN_PATH)
    if dev_reload_token is None:
        if token_path.exists():
            token_path.unlink()
        return
    token_path.parent.mkdir(parents=True, exist_ok=True)
    token_path.write_text(dev_reload_token + "\n", encoding="utf-8")


def write_social_card(output_dir: Path, resolved_card: ResolvedCard) -> None:
    """Write the managed social card asset when mkpages generates it."""
    output_path = output_dir / Path(SOCIAL_CARD_PATH)
    if not resolved_card.enabled or not resolved_card.generated:
        if output_path.exists():
            output_path.unlink()
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_social_card_svg(
            title=resolved_card.title,
            description=resolved_card.description,
            site_name=resolved_card.site_name,
            art_path=resolved_card.art_path,
            template_name=resolved_card.template,
        ),
        encoding="utf-8",
    )


def resolve_theme(
    content_root: Path,
    explicit_theme: str | Path | None,
    config_theme: str | None = None,
) -> ResolvedTheme:
    """Resolve the theme according to mkpages precedence rules."""
    root_theme = content_root / "theme.css"
    if root_theme.exists():
        return ResolvedTheme(path=root_theme, name=None)
    if explicit_theme is not None:
        return resolve_theme_value(explicit_theme)
    if config_theme:
        return resolve_theme_value(config_theme)

    return ResolvedTheme(path=bundled_theme_path("default"), name="default")


def resolve_theme_value(theme_value: str | Path) -> ResolvedTheme:
    """Resolve a configured theme value to either a built-in or filesystem path."""
    theme_name = str(theme_value).strip().lower()
    if theme_name in BUNDLED_THEMES:
        return ResolvedTheme(path=bundled_theme_path(theme_name), name=theme_name)

    theme_path = Path(theme_value).expanduser()
    if not theme_path.exists():
        choices = ", ".join(sorted(BUNDLED_THEMES))
        raise MkpagesError(f"theme file does not exist: {theme_path}. Built-in themes: {choices}")
    return ResolvedTheme(path=theme_path, name=None)


def bundled_theme_path(name: str) -> Path:
    """Return the installed resource path for a bundled theme."""
    resource = files("mkpages").joinpath(BUNDLED_THEMES[name])
    return Path(str(resource))


def render_template(template_name: str, **context: str) -> str:
    """Render a packaged text template with lightweight placeholders."""
    resource = files("mkpages").joinpath(f"{TEMPLATE_DIR}/{template_name}")
    rendered = resource.read_text(encoding="utf-8")
    for key, value in context.items():
        rendered = rendered.replace(f"[[ {key} ]]", value)
    return rendered


def build_navigation_markup(navigation: tuple[NavigationItem, ...]) -> str:
    """Render configured navigation links into the shared header include."""
    if not navigation:
        return ""

    lines = ['  <nav class="site-nav" aria-label="Primary">']
    for item in navigation:
        href = item.href.strip()
        if href.startswith("/"):
            href_markup = "{{ '" + href + "' | relative_url }}"
        else:
            href_markup = href
        lines.append(f'    <a href="{href_markup}">{escape_html(item.label)}</a>')
    lines.append("  </nav>")
    return "\n".join(lines)


def build_favicon_markup(favicon: PurePosixPath | None) -> str:
    """Render an optional favicon link tag for the shared layout."""
    if favicon is None:
        return ""

    href = "{{ '/" + favicon.as_posix() + "' | relative_url }}"
    return f'    <link rel="icon" href="{href}">'


def build_social_card_markup(resolved_card: ResolvedCard) -> str:
    """Render Open Graph and Twitter card metadata."""
    if not resolved_card.enabled:
        return ""

    image_href = "{{ '/" + resolved_card.image_path.as_posix() + "' | relative_url }}"
    return render_template(
        "social-card-meta.html.j2",
        title=escape_html(resolved_card.title),
        description=escape_html(resolved_card.description),
        site_name=escape_html(resolved_card.site_name),
        image=escape_html(image_href),
    )


def build_dev_reload_markup(dev_reload_token: str | None) -> str:
    """Render preview-only polling markup that survives Jekyll restarts."""
    if dev_reload_token is None:
        return ""
    token_url = "{{ '/" + DEV_RELOAD_TOKEN_PATH.as_posix() + "' | relative_url }}"
    token_json = json.dumps(dev_reload_token)
    return (
        "    <script>\n"
        f"      window.__MKPAGES_PREVIEW_TOKEN__ = {token_json};\n"
        f"      window.__MKPAGES_PREVIEW_TOKEN_URL__ = {json.dumps(token_url)};\n"
        "    </script>"
    )


def resolve_social_card(
    content_root: Path,
    site_title: str,
    site_description: str,
    card_config: CardConfig,
    theme_name: str | None,
    favicon: PurePosixPath | None,
) -> ResolvedCard:
    """Resolve automatic and configured social card settings."""
    card_template = resolve_card_template(theme_name, card_config.template)
    if not card_config.enabled:
        return ResolvedCard(
            enabled=False,
            title=site_title,
            description=site_description,
            site_name=site_title,
            template=card_template,
            image_path=SOCIAL_CARD_PATH,
            generated=False,
        )

    title = card_config.title or site_title
    description = card_config.description or site_description
    if card_config.image is not None:
        return ResolvedCard(
            enabled=True,
            title=title,
            description=description,
            site_name=site_title,
            template=card_template,
            image_path=card_config.image,
            generated=False,
        )

    return ResolvedCard(
        enabled=True,
        title=title,
        description=description,
        site_name=site_title,
        template=card_template,
        image_path=SOCIAL_CARD_PATH,
        generated=True,
        art_path=resolve_card_art(content_root, favicon, card_config.logo),
    )


def resolve_card_template(theme_name: str | None, configured_template: str | None) -> str:
    """Resolve the effective card template from explicit config or theme defaults."""
    if configured_template is not None:
        template_name = configured_template.strip().lower()
    else:
        template_name = THEME_CARD_TEMPLATES.get(theme_name or "", "default")

    if template_name not in SUPPORTED_CARD_TEMPLATES:
        choices = ", ".join(sorted(SUPPORTED_CARD_TEMPLATES))
        raise MkpagesError(
            f"unsupported card template: {template_name}. Built-in card templates: {choices}"
        )
    return template_name


def resolve_card_art(
    content_root: Path,
    favicon: PurePosixPath | None,
    configured_logo: PurePosixPath | None,
) -> Path | None:
    """Resolve a configured favicon or logo path for card generation."""
    if favicon is not None:
        favicon_path = content_root / Path(favicon)
        if favicon_path.exists() and favicon_path.is_file():
            return favicon_path

    if configured_logo is not None:
        logo_path = content_root / Path(configured_logo)
        return logo_path if logo_path.exists() and logo_path.is_file() else None

    for relative_path in (
        PurePosixPath("logo.svg"),
        PurePosixPath("logo.png"),
        PurePosixPath("assets/logo.svg"),
        PurePosixPath("assets/logo.png"),
        PurePosixPath("images/logo.svg"),
        PurePosixPath("images/logo.png"),
    ):
        candidate = content_root / Path(relative_path)
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def render_social_card_svg(
    title: str,
    description: str,
    site_name: str,
    art_path: Path | None,
    template_name: str,
) -> str:
    """Render a managed SVG social card from a bundled packaged template."""
    context = build_social_card_context(title, description, site_name, art_path, template_name)
    return render_template(
        f"social-card-{template_name}.svg.j2",
        title=context.title,
        site_name=context.site_name,
        description_markup=context.description_markup,
        logo_markup=context.logo_markup,
        title_x=context.title_x,
        title_y=context.title_y,
    )


def build_social_card_context(
    title: str,
    description: str,
    site_name: str,
    art_path: Path | None,
    template_name: str,
) -> SocialCardContext:
    """Build the render context for the bundled default social card template."""
    title_x = "88"
    title_y = "184"
    description_fill = "#52607a"
    description_y = 316
    description_line_length = 40
    if template_name == "dark":
        description_fill = "#a0aec0"
        description_y = 316
        description_line_length = 40
    logo_markup = ""
    if art_path is not None:
        encoded_logo = encode_data_uri(art_path)
        if encoded_logo is not None:
            logo_x = 960
            logo_y = 94
            logo_width = 136
            logo_height = 136
            logo_opacity = "0.96"
            logo_filter = ""
            if template_name == "default":
                logo_x = 790
                logo_y = 90
                logo_width = 324
                logo_height = 444
                logo_opacity = "0.12"
            if template_name == "dark":
                logo_x = 700
                logo_y = 10
                logo_width = 470
                logo_height = 630
                logo_opacity = "0.22"
                logo_filter = ' filter="url(#art-darken)"'
            logo_markup = (
                f'  <image href="{encoded_logo}" x="{logo_x}" y="{logo_y}" width="{logo_width}" '
                f'height="{logo_height}" preserveAspectRatio="xMidYMid meet" opacity="{logo_opacity}"{logo_filter}/>\n'
            )

    return SocialCardContext(
        title=escape_html(truncate_text(title, 40)),
        site_name=escape_html(truncate_text(site_name, 18).upper()),
        description_markup=render_svg_text_lines(
            wrap_text(description, description_line_length, max_lines=2),
            x=88,
            y=description_y,
            line_height=40,
            fill=description_fill,
            font_size=30,
            font_weight="400",
        ),
        logo_markup=logo_markup,
        description_fill=description_fill,
        title_x=title_x,
        title_y=title_y,
    )


def render_svg_text_lines(
    lines: tuple[str, ...],
    x: int,
    y: int,
    line_height: int,
    fill: str,
    font_size: int,
    font_weight: str,
) -> str:
    """Render one or more SVG text lines with tspans."""
    if not lines:
        return ""
    tspans = []
    for index, line in enumerate(lines):
        dy = "0" if index == 0 else str(line_height)
        tspans.append(f'<tspan x="{x}" dy="{dy}">{escape_html(line)}</tspan>')
    return (
        f'  <text x="{x}" y="{y}" fill="{fill}" font-family="Segoe UI, Arial, sans-serif" '
        f'font-size="{font_size}" font-weight="{font_weight}">' + "".join(tspans) + "</text>\n"
    )


def encode_data_uri(path: Path) -> str | None:
    """Encode a local image file as a data URI for SVG embedding."""
    media_types = {
        ".svg": "image/svg+xml",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }
    media_type = media_types.get(path.suffix.lower())
    if media_type is None:
        return None
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{media_type};base64,{encoded}"


def truncate_text(text: str, limit: int) -> str:
    """Trim long card text without splitting the feature across config and rendering."""
    stripped = " ".join(text.split())
    if len(stripped) <= limit:
        return stripped
    return stripped[: limit - 1].rstrip() + "…"


def wrap_text(text: str, line_length: int, max_lines: int) -> tuple[str, ...]:
    """Wrap plain text into a small number of display lines."""
    words = " ".join(text.split()).split()
    if not words:
        return ()

    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if len(candidate) <= line_length:
            current = candidate
            continue
        lines.append(current)
        current = word
        if len(lines) == max_lines - 1:
            break

    remaining_words = words[len(" ".join(lines + [current]).split()) :]
    if len(lines) < max_lines:
        tail = " ".join([current] + remaining_words).strip()
        lines.append(truncate_text(tail, line_length))
    return tuple(lines[:max_lines])


def escape_html(text: str) -> str:
    """Escape a plain string for safe inclusion in generated HTML."""
    return (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")
    )


def load_site_config(content_root: Path) -> SiteConfig:
    """Load optional mkpages.yml configuration from the content root."""
    config_path = content_root / CONFIG_FILE_NAME
    if not config_path.exists():
        return SiteConfig()

    return parse_site_config(config_path.read_text(encoding="utf-8"), config_path)


def parse_site_config(raw_text: str, config_path: Path) -> SiteConfig:
    """Parse the supported mkpages.yml subset used in v1."""
    lines = raw_text.splitlines()
    scalars: dict[str, str] = {}
    navigation: list[NavigationItem] = []
    card_config = CardConfig()
    index = 0

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        index += 1

        if not stripped or stripped.startswith("#"):
            continue

        if line.startswith((" ", "\t")):
            raise MkpagesError(f"invalid indentation in {config_path}")

        if stripped == "navigation:":
            items, index = parse_navigation_block(lines, index, config_path)
            navigation.extend(items)
            continue
        if stripped == "card:":
            card_config, index = parse_card_block(lines, index, config_path)
            continue

        key, separator, value = stripped.partition(":")
        if not separator:
            raise MkpagesError(f"invalid config line in {config_path}: {stripped}")
        scalars[key.strip()] = strip_yaml_scalar(value.strip())

    return SiteConfig(
        title=scalars.get("title"),
        description=scalars.get("description"),
        theme=scalars.get("theme"),
        favicon=parse_site_asset_path(config_path, "favicon", scalars.get("favicon")),
        navigation=tuple(navigation),
        card=card_config,
    )


def parse_site_asset_path(
    config_path: Path, key: str, raw_value: str | None
) -> PurePosixPath | None:
    """Validate a configured site asset path relative to the content root."""
    if raw_value is None:
        return None

    normalized = PurePosixPath(raw_value.strip())
    if raw_value.strip().startswith("/"):
        raise MkpagesError(
            f"{key} in {config_path} must be a relative path inside the content root"
        )
    if normalized.is_absolute():
        raise MkpagesError(
            f"{key} in {config_path} must be a relative path inside the content root"
        )

    parts = normalized.parts
    if not parts or any(part in {"", ".", ".."} for part in parts):
        raise MkpagesError(f"{key} in {config_path} must not use empty, '.' or '..' path segments")
    if any(
        any(ch in part for ch in {"'", '"', "<", ">", "\\", "\n", "\r", "\t"}) for part in parts
    ):
        raise MkpagesError(
            f"{key} in {config_path} must not contain quotes, angle brackets, backslashes, or control characters"
        )

    asset_path = config_path.parent.joinpath(*parts)
    if not asset_path.exists() or not asset_path.is_file():
        raise MkpagesError(f"{key} file does not exist: {asset_path}")
    if is_excluded(Path(*parts)):
        raise MkpagesError(f"{key} in {config_path} must not point to a hidden or excluded path")
    return normalized


def parse_navigation_block(
    lines: list[str], start_index: int, config_path: Path
) -> tuple[list[NavigationItem], int]:
    """Parse a simple YAML list of navigation items."""
    items: list[NavigationItem] = []
    index = start_index

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()

        if not stripped or stripped.startswith("#"):
            index += 1
            continue
        if not line.startswith("  "):
            break
        if not stripped.startswith("- "):
            raise MkpagesError(f"invalid navigation entry in {config_path}: {stripped}")

        item_fields: dict[str, str] = {}
        first_field = stripped[2:]
        if first_field:
            key, separator, value = first_field.partition(":")
            if not separator:
                raise MkpagesError(f"invalid navigation entry in {config_path}: {stripped}")
            item_fields[key.strip()] = strip_yaml_scalar(value.strip())
        index += 1

        while index < len(lines):
            nested_line = lines[index]
            nested_stripped = nested_line.strip()
            if not nested_stripped or nested_stripped.startswith("#"):
                index += 1
                continue
            if not nested_line.startswith("    "):
                break

            key, separator, value = nested_stripped.partition(":")
            if not separator:
                raise MkpagesError(f"invalid navigation field in {config_path}: {nested_stripped}")
            item_fields[key.strip()] = strip_yaml_scalar(value.strip())
            index += 1

        label = item_fields.get("label")
        href = item_fields.get("href")
        if not label or not href:
            raise MkpagesError(f"navigation items in {config_path} require label and href")
        items.append(NavigationItem(label=label, href=href))

    return items, index


def parse_card_block(
    lines: list[str], start_index: int, config_path: Path
) -> tuple[CardConfig, int]:
    """Parse a simple nested card configuration mapping."""
    fields: dict[str, str] = {}
    index = start_index

    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            index += 1
            continue
        if not line.startswith("  "):
            break
        if line.startswith("    "):
            raise MkpagesError(f"invalid card field indentation in {config_path}: {stripped}")

        key, separator, value = stripped.partition(":")
        if not separator:
            raise MkpagesError(f"invalid card field in {config_path}: {stripped}")
        fields[key.strip()] = strip_yaml_scalar(value.strip())
        index += 1

    enabled_value = fields.get("enabled")
    enabled = True if enabled_value is None else bool(parse_scalar_value(enabled_value))
    return (
        CardConfig(
            enabled=enabled,
            template=fields.get("template"),
            title=fields.get("title"),
            description=fields.get("description"),
            logo=parse_site_asset_path(config_path, "card.logo", fields.get("logo")),
            image=parse_site_asset_path(config_path, "card.image", fields.get("image")),
        ),
        index,
    )


def strip_yaml_scalar(value: str) -> str:
    """Strip optional single or double quotes from a simple scalar."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def infer_site_title(content_root: Path) -> str:
    """Infer a usable site title from the content root location."""
    root_name = content_root.resolve().name
    if root_name.lower() in {"docs", "doc", "documentation"}:
        parent = content_root.resolve().parent.name
        if parent:
            return parent
    return root_name or "mkpages"


def build_content_index(
    content_root: Path, page_map: dict[PurePosixPath, Page]
) -> dict[str, tuple[ContentEntry, ...]]:
    """Build a simple index of front-matter-backed content by top-level folder."""
    index: dict[str, list[ContentEntry]] = {}
    for source_rel, page in page_map.items():
        if source_rel.name == "index.md":
            continue
        if not source_rel.parts:
            continue

        source_path = content_root / Path(source_rel)
        front_matter, body = split_front_matter(source_path.read_text(encoding="utf-8"))
        metadata = parse_front_matter(front_matter)
        title = str(metadata.get("title") or extract_title(body, fallback_title(source_rel)))
        description = str(metadata.get("description") or metadata.get("excerpt") or "")
        entry = ContentEntry(page=page, title=title, description=description, metadata=metadata)
        index.setdefault(source_rel.parts[0], []).append(entry)

    for key, entries in index.items():
        index[key] = sorted(entries, key=content_entry_sort_key)
    return {key: tuple(entries) for key, entries in index.items()}


def content_entry_sort_key(entry: ContentEntry) -> tuple[object, ...]:
    """Sort entries for directive rendering."""
    order = entry.metadata.get("order")
    date = str(entry.metadata.get("date") or "")
    return (
        0 if isinstance(order, int) else 1,
        order if isinstance(order, int) else 0,
        -1 if date else 0,
        date,
        entry.title.lower(),
    )


def write_page(
    content_root: Path,
    output_dir: Path,
    page: Page,
    page_map: dict[PurePosixPath, Page],
    content_index: dict[str, tuple[ContentEntry, ...]],
) -> None:
    """Generate one markdown page with front matter and rewritten local links."""
    source_path = content_root / Path(page.source_rel)
    raw_content = source_path.read_text(encoding="utf-8")
    front_matter, body = split_front_matter(raw_content)
    rewritten_body = rewrite_local_links(body, page, page_map)
    expanded_body = expand_directives(rewritten_body, content_index)

    front_matter_text = ensure_front_matter(
        front_matter,
        title=extract_title(expanded_body, fallback_title(page.source_rel)),
    )
    rendered = front_matter_text + "\n" + expanded_body.lstrip("\n")

    destination = output_dir / Path(page.output_rel)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(rendered, encoding="utf-8")


def split_front_matter(content: str) -> tuple[str | None, str]:
    """Split optional YAML front matter from a markdown document."""
    match = FRONT_MATTER_RE.match(content)
    if not match:
        return None, content
    return match.group("front"), content[match.end() :]


def parse_front_matter(front_matter: str | None) -> dict[str, object]:
    """Parse the small YAML subset used in markdown front matter."""
    if not front_matter:
        return {}

    result: dict[str, object] = {}
    lines = front_matter.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        index += 1
        if not stripped or stripped.startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            continue

        key, separator, value = stripped.partition(":")
        if not separator:
            continue
        key = key.strip()
        value = value.strip()
        if not value:
            items: list[str] = []
            while index < len(lines):
                nested = lines[index]
                nested_stripped = nested.strip()
                if not nested_stripped or nested_stripped.startswith("#"):
                    index += 1
                    continue
                if not nested.startswith("  - "):
                    break
                items.append(strip_yaml_scalar(nested_stripped[2:].strip()))
                index += 1
            result[key] = items
            continue

        result[key] = parse_scalar_value(strip_yaml_scalar(value))
    return result


def parse_scalar_value(value: str) -> object:
    """Parse a simple YAML scalar into a small Python value."""
    lowered = value.lower()
    if lowered == "true":
        return True
    if lowered == "false":
        return False
    if re.fullmatch(r"-?\d+", value):
        try:
            return int(value)
        except ValueError:
            return value
    return value


def ensure_front_matter(front_matter: str | None, title: str) -> str:
    """Return front matter that guarantees layout and title keys."""
    if not front_matter:
        return f"---\nlayout: default\ntitle: {json.dumps(title)}\n---\n"

    keys = set(FRONT_MATTER_KEY_RE.findall(front_matter))
    lines = [line.rstrip("\n") for line in front_matter.splitlines()]
    if "layout" not in keys:
        lines.append("layout: default")
    if "title" not in keys:
        lines.append(f"title: {json.dumps(title)}")
    return "---\n" + "\n".join(lines) + "\n---\n"


def expand_directives(content: str, content_index: dict[str, tuple[ContentEntry, ...]]) -> str:
    """Expand supported mkpages directives into HTML blocks."""

    def replace(match: re.Match[str]) -> str:
        name = match.group("name")
        if name != "cards":
            return match.group(0)
        args = parse_directive_args(match.group("args"))
        return render_cards_directive(args, content_index)

    return CARDS_DIRECTIVE_RE.sub(replace, content)


def parse_directive_args(raw_args: str) -> dict[str, str]:
    """Parse key=value directive arguments from a single line."""
    return {
        match.group("key"): match.group("value") for match in DIRECTIVE_ARG_RE.finditer(raw_args)
    }


def render_cards_directive(
    args: dict[str, str], content_index: dict[str, tuple[ContentEntry, ...]]
) -> str:
    """Render a simple cards grid from indexed content."""
    source = args.get("source", "").strip().strip("\"'")
    if not source:
        raise MkpagesError(":::cards requires source=...")

    entries = list(content_index.get(source, ()))
    if parse_bool_arg(args.get("featured")):
        entries = [entry for entry in entries if bool(entry.metadata.get("featured"))]

    limit = parse_int_arg(args.get("limit"))
    if limit is not None:
        entries = entries[:limit]

    columns = parse_int_arg(args.get("columns")) or 2
    columns = max(1, min(columns, 4))

    lines = [f'<div class="card-grid card-grid-{columns}">']
    for entry in entries:
        description = escape_html(entry.description)
        title = escape_html(entry.title)
        href = escape_html(entry.page.route_url)
        tags = entry.metadata.get("tags")
        lines.append('  <article class="content-card">')
        lines.append(f'    <h3><a href="{href}">{title}</a></h3>')
        if description:
            lines.append(f"    <p>{description}</p>")
        if isinstance(tags, list) and tags:
            tag_markup = " ".join(
                f'<span class="card-tag">{escape_html(str(tag))}</span>' for tag in tags[:3]
            )
            lines.append(f'    <div class="card-tags">{tag_markup}</div>')
        lines.append("  </article>")
    lines.append("</div>")
    return "\n".join(lines)


def parse_bool_arg(value: str | None) -> bool:
    """Parse an optional boolean directive argument."""
    if value is None:
        return False
    return value.strip().strip("\"'").lower() == "true"


def parse_int_arg(value: str | None) -> int | None:
    """Parse an optional integer directive argument."""
    if value is None:
        return None
    stripped = value.strip().strip("\"'")
    if not re.fullmatch(r"\d+", stripped):
        return None
    return int(stripped)


def extract_title(content: str, fallback: str) -> str:
    """Extract the first markdown H1 or fall back to a generated title."""
    match = H1_RE.search(content)
    if match:
        return match.group("title").strip()
    return fallback


def fallback_title(source_rel: PurePosixPath) -> str:
    """Build a title from the source file location."""
    if source_rel.name in {"index.md", "README.md"} and str(source_rel.parent) not in {"", "."}:
        token = source_rel.parent.name
    elif source_rel.name in {"index.md", "README.md"}:
        token = "Home"
    else:
        token = source_rel.stem
    return token.replace("-", " ").replace("_", " ").title()


def rewrite_local_links(content: str, page: Page, page_map: dict[PurePosixPath, Page]) -> str:
    """Rewrite local markdown links so they still work after route generation."""

    def replace(match: re.Match[str]) -> str:
        raw_target = match.group("target").strip()
        target, suffix = split_target_suffix(raw_target)
        if not target:
            return match.group(0)
        if is_external_target(target):
            return match.group(0)

        path_part, fragment = split_fragment(target)
        if not path_part:
            return match.group(0)
        if path_part.startswith("/"):
            return match.group(0)

        resolved_source = normalize_relative_path(page.source_rel.parent, path_part)
        if path_part.endswith(".md"):
            rewritten = rewrite_markdown_target(page, resolved_source, fragment, page_map)
        else:
            rewritten = rewrite_asset_target(page, resolved_source, fragment)

        return f"{match.group('prefix')}{rewritten}{suffix}{match.group('suffix')}"

    return MARKDOWN_LINK_RE.sub(replace, content)


def split_target_suffix(target: str) -> tuple[str, str]:
    """Separate a markdown link destination from any optional title suffix."""
    stripped = target.strip()
    if stripped.startswith("<") and ">" in stripped:
        end = stripped.find(">")
        return stripped[1:end], stripped[end + 1 :]

    parts = stripped.split(maxsplit=1)
    if not parts:
        return "", ""
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], " " + parts[1]


def is_external_target(target: str) -> bool:
    """Return True if a markdown target should not be rewritten."""
    if target.startswith(("#", "mailto:", "tel:", "//")):
        return True
    return bool(re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target))


def split_fragment(target: str) -> tuple[str, str]:
    """Split a URL fragment from the main path."""
    path, separator, fragment = target.partition("#")
    if not separator:
        return path, ""
    return path, "#" + fragment


def normalize_relative_path(base_dir: PurePosixPath, target: str) -> PurePosixPath:
    """Normalize a relative POSIX path without touching the host filesystem."""
    combined = base_dir.joinpath(PurePosixPath(target))
    parts: list[str] = []
    for part in combined.parts:
        if part in {"", "."}:
            continue
        if part == "..":
            if parts:
                parts.pop()
            continue
        parts.append(part)
    if not parts:
        return PurePosixPath(".")
    return PurePosixPath(*parts)


def rewrite_markdown_target(
    page: Page,
    resolved_source: PurePosixPath,
    fragment: str,
    page_map: dict[PurePosixPath, Page],
) -> str:
    """Rewrite a markdown link to the generated route for its destination."""
    target_page = page_map.get(resolved_source)
    if target_page is None:
        target_route = route_for(resolved_source, set(page_map))
    else:
        target_route = target_page.route_rel
    rewritten = relative_route(page.route_rel, target_route, is_dir=True)
    return rewritten + fragment


def rewrite_asset_target(page: Page, resolved_source: PurePosixPath, fragment: str) -> str:
    """Rewrite an asset path relative to the generated route."""
    rewritten = relative_route(page.route_rel, resolved_source, is_dir=False)
    return rewritten + fragment


def relative_route(current_route: PurePosixPath, target_rel: PurePosixPath, is_dir: bool) -> str:
    """Return a relative link from one generated route to another target."""
    current = "." if str(current_route) in {"", "."} else current_route.as_posix()
    target = "." if str(target_rel) in {"", "."} else target_rel.as_posix()
    rewritten = os.path.relpath(target, start=current).replace(os.sep, "/")
    if rewritten == ".":
        return "./" if is_dir else "."
    if is_dir and not rewritten.endswith("/"):
        return rewritten + "/"
    return rewritten


def copy_non_markdown_files(content_root: Path, output_dir: Path) -> int:
    """Copy non-markdown files into the generated output tree."""
    copied = 0
    for path in sorted(content_root.rglob("*")):
        if path.is_dir():
            continue
        rel_path = path.relative_to(content_root)
        if (
            is_excluded(rel_path)
            or path.suffix.lower() == ".md"
            or rel_path.name == CONFIG_FILE_NAME
        ):
            continue
        destination = output_dir / rel_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, destination)
        copied += 1
    return copied


def is_excluded(rel_path: Path) -> bool:
    """Return True if a path is hidden or under one of the excluded names."""
    for part in rel_path.parts:
        if part in EXCLUDED_NAMES:
            return True
        if part not in {".", ".."} and part.startswith("."):
            return True
    return False
